/* Generated by scripts/build-art-manifest.mjs - do not edit by hand.

   Which art files actually exist in assets/. The portrait component checks this
   before requesting anything, so a breed without art falls straight back to the
   generated swatch instead of firing a request that 404s.

   0 files at last build. Re-run
   `npm run art:manifest` after adding more. */
const ART_MANIFEST = new Set([]);
function hasArt(rel) { return ART_MANIFEST.has(rel); }
